import '../globals.css'
import {Inter} from 'next/font/google'
import {AppContextProvider} from "@/contexts/AppContext";

const inter = Inter({subsets: ['latin']})

// i18n
import {NextIntlClientProvider} from 'next-intl';
import {notFound} from 'next/navigation';

export function generateStaticParams() {
    return [{locale: 'en'}, {locale: 'es'}];
}

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default async function RootLayout({children, params: {locale}}: {children: React.ReactNode, params: any}) {

    let messages;
    try {
        messages = (await import(`../../messages/${locale}.json`)).default;
    } catch (error) {
        notFound();
    }

    return (
        <html lang={locale}>
            <body className={inter.className}>
                <NextIntlClientProvider locale={locale} messages={messages}>
                    <AppContextProvider>{children}</AppContextProvider>
                </NextIntlClientProvider>
            </body>
        </html>
    )
}
